import React, { useEffect, useState } from "react";
import { Download, FileBarChart2 } from "lucide-react";
import PageHeader from "../components/PageHeader";
import { fetchReports, reportDownloadUrl } from "../api/analyticsApi";
import { listResource } from "../api/resources";

export default function Reports(){
 const [stores,setStores]=useState([]),[storeId,setStoreId]=useState(""),[hours,setHours]=useState(24),[data,setData]=useState({attention:[],products:[]}),[error,setError]=useState("");
 useEffect(()=>{listResource("stores").then(x=>{setStores(x);if(x[0]?.id)setStoreId(x[0].id)}).catch(()=>setError("Unable to load stores."))},[]);
 useEffect(()=>{if(storeId)fetchReports(storeId,hours).then(setData).catch(e=>setError(e.response?.data?.detail||"Unable to load reports."))},[storeId,hours]);
 const download=(kind)=>window.open(reportDownloadUrl(kind,storeId,hours),"_blank");
 return <div className="mx-auto max-w-7xl"><PageHeader title="Reports & exports" description="Download attention and product intelligence reports generated by the CAMS backend." actions={<div className="flex gap-2"><select value={storeId} onChange={e=>setStoreId(e.target.value)}><option value="">Store</option>{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select value={hours} onChange={e=>setHours(Number(e.target.value))}><option value="6">6 hours</option><option value="24">24 hours</option><option value="168">7 days</option></select></div>}/>{error&&<div className="mb-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
 <div className="grid gap-4 md:grid-cols-3">{[{kind:"attention.csv",title:"Attention CSV",text:`${data.attention.length} attention rows`},{kind:"attention.pdf",title:"Attention PDF",text:"Printable attention report"},{kind:"products.xlsx",title:"Products Excel",text:`${data.products.length} product rows`}].map(x=><article key={x.kind} className="rounded-xl border bg-white p-5 shadow-sm"><FileBarChart2 size={20}/><h2 className="mt-3 font-semibold">{x.title}</h2><p className="mt-1 text-sm text-slate-500">{x.text}</p><button disabled={!storeId} onClick={()=>download(x.kind)} className="mt-5 inline-flex items-center gap-2 rounded-lg bg-slate-950 px-4 py-2 text-sm text-white disabled:opacity-40"><Download size={14}/> Download</button></article>)}</div>
 </div>
}
